name: Build
on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g npm@7
      - run: npm ci
      - name: Run Build
        run: npm run build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Commit report
        run: |
          git config --global user.name 'Dan Gowans'
          git config --global user.email 'dangowans@users.noreply.github.com'
          git commit -am "Latest data"
          git push
